import Head from "next/head";

interface Props {
  title: string;
}

export default function BaseHeader({ title }: Props) {
  return (
    <Head>
      <title>{title} | Eventful</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
